### ISSUE TITLE
Zoom F6 Timecode not working?

### ISSUE THREAD

**Issue by chrisspiegl** [arikrupnik/ltcsync#28]
Hello there, I just tried out this tool and wondered why my timecode would not work as the samples do.
I am trying to understand how it all works and also how you implemented things. Also would love to use it for my projects.
Anyways, here is what is happening:

- Shoot video on Canon EOS R with TC coming into right channel from the Zoom F6 TC Out Port.
- Take the recorded file from EOS R into LTCSync and it only shows up without Start TC as "Files without embedded timecode"

I also have tried the same thing with files recorded to the Atomos Ninja V with the TC coming from F6 to EOS R to Atomos Recorder via HDMI.

Any idea here?
Am I missing something?
A setting maybe?

Because I am seeing the Zoom files in the samples folder that apparently got tracked correctly?

I hope we can figure this out.

Cheers, Chris

**Comment by arikrupnik** [comment]
Thank you for your note, @chrisspiegl . If you can share a short video file with embedded LTC, it would help answer your question. Can you hear it if you play back the video file? What does the audio track look like in an editor?

**Comment by chrisspiegl** [comment]
Ofcourse, here is the extracted audio channel. I tried putting this into LTCsync and it did not read to have a timecode embedded.

I also tried running it directly through `ltcdump` but even that does not return any information. Maybe I have to open an issue there as well?

[CSP_8307-1-right.wav.zip](https://github.com/arikrupnik/ltcsync/files/5497405/CSP_8307-1-right.wav.zip)

**Comment by arikrupnik** [comment]
Thank you for the sample, @chrisspiegl. You are correct that if `ltcdump` cannot parse TC out of a sound file, `ltcsync` cannot either. But it isn't clear to me that it is an `ltcdump` issue either. Your waveform (top in my screenshot) looks  very faint--compare to waveform (bottom) from one of my samples.
![ltc-amplitude](https://user-images.githubusercontent.com/1756197/98298053-fe6d9e00-1f7a-11eb-85b6-8ae85fa64744.png). It does resemble LTC. Sadly, it looks too noisy to parse. I can amplify the samples, but they are still unreadable.

Can you elaborate on your cabling from the F6 to the camera?

**Comment by chrisspiegl** [comment]
Hi @arikrupnik, thank you for your reply and insights. As you have seen I also opened an issue with the `libltc` project since it may be based there. But maybe your understanding here also helps.

To reduce the error possibilities, I decided to use the Rode VXLR+ adapter to plug the TC output of the Zoom F6 into itself and record a TC sample with 32bit float.

I tried putting this file through `ltcsync` and `ltcdump` but both could not read the TC from the audio file.
In Audition the wave file looks fine. And interestingly enough the `Tentacle Sync Studio` can read the audio TC.

[201105_009_Tr1.WAV.zip](https://github.com/arikrupnik/ltcsync/files/5497573/201105_009_Tr1.WAV.zip)


One more addition to my thinking: I am currently using a Stereo cable for this test? May this be the issue?

**Comment by chrisspiegl** [comment]
Adding to the collection of test files… maybe this is just me being stupid with timecode audio…

Here I plugged a L/R splitter into the TC out of the Zoom F6 and then separately recorded the left and right channel with stereo mini jack aux cables to the zoom f6.

The same result, none of the two could be read by `ltcdump`.

Maybe you have an idea about what may be going on here? I am that this may not have anything to do with the program but more with my own knowledge/setup.

[left-right-channel-test.zip](https://github.com/arikrupnik/ltcsync/files/5497697/left-right-channel-test.zip)

In this comparison, the "right channel" file is able to be read as audio TC by the `Tentacle Sync Studio`.

I am pretty sure they have their own implementation, and do not use `ltcdump` but it's interesting that it is possible to be read non the less.

**Comment by arikrupnik** [comment]
Can you take a photo of your cabling? F6 uses a 3.5mm socket for TC. EOS R uses 3.5mm socket for mic input. I'm unclear on where you're suing an XLR adapter. I expect you should be able to plug a simple stereo cable between F6 and your camera, and get timecode on the right channel (and silence on the left). F6 uses an unusual pinout where the tip is TC input and ring is TC output.

Separately, do you have your audio recording level in the camera set to `auto` or `manual`? It's possible your audio gains are too low.

**Comment by chrisspiegl** [comment]
I am trying to remove variables from the test, that is why I am trying to record the TC into the Zoom F6 with the 3.5mm to XLR adapter. As seen in the following photo:

![IMG_9583](https://user-images.githubusercontent.com/1096384/98302435-aa83a900-1fbc-11eb-8bb4-19abe8661498.jpg)

The recorded audio is practically the same as it is with the recording into the Canon EOS R and the issues are also the same.

If it would only be the audio gain being too low, the 32bit float should not have any problems whatsoever. But the problem persists.

**Comment by arikrupnik** [comment]
> To reduce the error possibilities, I decided to use the Rode VXLR+ adapter to plug the TC output of the Zoom F6 into itself and record a TC sample with 32bit float.

The XLR adapter probably doesn't do what you think it does. Get a left-right spiltter (I thin you have that) and a1/8"-to1/4" adapter, plug the 1/4" end into F6. Ignore the left. The left (tip) on the F6 TC socket is input, so it's going to produce no signal on it.

Turn up the gain on the channel where you're recording the TC. All that 32-bit stuff is lost when you export your WAV. The first file you sent me has 16-bit resolution.

**Comment by chrisspiegl** [comment]
I am not sure what you think that I think the XLR adapter is doing?

The first WAV file was extracted from a Canon EOS R recording. As mentioned before, I am trying to now reduce components and thus moved to recording the TC on the F6. That's why now the new files are 32bit in this example [left-right-channel.zip](https://github.com/arikrupnik/ltcsync/files/5497697/left-right-channel-test.zip).

This helped me understand that the left channel does what you described in the last message (be input, and the right the supposed TC signal).

But it does not explain why the TC signal is so noisy?

**Comment by chrisspiegl** [comment]
I have one more test setup here with an example file:

![IMG_9584](https://user-images.githubusercontent.com/1096384/98303253-1d415400-1fbe-11eb-87fa-041488444a98.jpg)

[201105_014_Tr1.WAV.zip](https://github.com/arikrupnik/ltcsync/files/5497785/201105_014_Tr1.WAV.zip)

This still shows the same noise. At this point, I am not sure where these things are coming from. If it's the cable I am using or the TC output of the F6. But I also don't want to waste your time with this since it is pretty clear to me that it's not something `ltcsync` has anything to do with.

I appreciate any input you gave here and I hope I can figure it out sometime. If you have any other suggestions. I'd be glad to hear about them.

Thank you again.

**Comment by arikrupnik** [comment]
We're both typing too fast, I can't keep up :=) Thank you for the photos. My XLR remark is probably misplaced.

I agree that it's not an `'ltcsync` issue as such. I'm glad some of my comments are useful regardless.

The waveform in your 32-bit files still looks strange. It has the general form of LTC that I'm familiar with, but instead of a square wave like in my sample above, it seems to have single peaks for each pulse. Perhaps this is a peculiarity of the F6. I don't have an F6 to test this theory. If it is true, it would seem that Tentacle can decode this non-standard waveform and `libltc` decodes only the standard square wave.

![Screenshot_2020-11-05_16-32-27](https://user-images.githubusercontent.com/1756197/98303884-873d0780-1f84-11eb-8efb-866dea271da0.png)

It is also possible that the recorder has some kind of filter that interprets the unnatural-sounding square wave into something more plausible. I doubt this is it, but you may want to check the menus to make sure no filters are active.

I would recommend using a simple 1/8" stereo from F6 TC to your EOS, and turn the audio gains up there. Make sure you turn off wind noise filters and such. If you have another piece of recording equipment, like a USB stereo input, you might try that, and see if you get the same spiky waveform there, or a more rectangular-looking wave.

Let me know if any of these produce any different results.

**Comment by chrisspiegl** [comment]
I appreciate your thoughts and input. It's been great trying to figure this out. Even though I do not have a solution up to this point. It has become clear that it's neither `ltcsync` nore `ltcdump` that are the issue here. It has something todo with my setup/cables or similar. I will have to see how I can figure this out and debug this mess.

Maybe I have to try some Mono-Cables at some point or something… since I am not doing anything else that I know of.

Cheers and thanks again for your help.

**Comment by arikrupnik** [comment]
When you do figure it out, please post here so that others who find your question may learn from your investigation.

**Comment by chrisspiegl** [comment]
Not necessarily done with the exploration, but I think I have found the issue and it's two sided:

1. The first issue is that the Zoom F6 outputs the TC signal on line level which means it's super loud. The Canon EOS R has only a mic level input and thus the camera seems to have problems recording the signal and it gets attenuated internally which in turn destroys the signal.
2. The second issue is the use of stereo cables and the adapter I am using. The adapter cable (left/right splitter) seems to be working differently than I am expecting. May report further as I find more info.

**What worked:**

I recently also purchased a Attentuator cable which takes a stereo line-level signal on one side and then outputs a mic level signal on the other. If I **ONLY** use that cable between the Zoom F6 TC port and the Canon EOS R input port, the TC signal is actually readable by `ltcdump` and thus also by `ltcsync`.

The other thing that worked was using a stereo aux cable to connect the Zoom F6 TC port directly to the Atomos Ninja V 3.5mm mic/line input which can be toggled between mic and line level. Set to line level there, it works per expectation.

**Next Test:**

I have ordered some 3.5mm stereo to mono adapters to test a theory if I can get it working with those a bit easier with the idea being that I can send a signal to the Canon EOS R. But I'll see about that 🙈.

**Possible Improvements**

I will be talking to the Zoom support team. They may be able to implement two things to mitigate these types of issues:

1. Outputting the TC signal in either Mic or Line level would help a great deal.
2. The ability to switch on/off the receiver/sender.
3. The ability to switch the receiver and sender channel (some cameras are not consistent in this regard).

Will report as I know more.

**Comment by arikrupnik** [comment]
While most mic-level inputs are not rated for line-level input, in practice every one I've seen can cope with the voltages. Pushing line-level audio into mic-level input results in horrible clipping. But LTC is not audio--it's a square wave, and clipping it changes nothing in the waveform. I have a Canon 60D with mic-level inputs, and it can take line-level LTC all day.

**Comment by chrisspiegl** [comment]
@arikrupnik That "should be true" 🙈  😢  indeed — and it would be great if it would.

Sadly the Canon EOS R — and some other Canon cameras I have heard about — seem to have changed this behavior. They do not handle the Line level signal very well at all. Hence the attenuation cable actually does fix the issue.

I have done many tests regarding this and also have seen others work a similar issue with this. One can even see the attenuation in the Line out Test tone the F6 produces and it's reminding me of the same strange curve the Timecode signal shows as well with the spikes but then the rest is flattened.

I will share more examples once I have the mono adapter to rule more stuff out.
